### ISSUE TITLE
Issues found while flood testing on 07/04/17

### ISSUE THREAD

**Issue by GitSquared** [GitSquared/ORNE-server#1]
- [ ] ws.send() throws an uncaught exception when the client already disconnected from the websocket
- [x] any uncaught exception makes the whole process die, maybe restart the worker processes on death?
- [x] need some optimization on emails, they're too big

**Comment by GitSquared** [comment]
Additional info on ws.send() error
```
EXCEPTION: 
Error: not opened
    at WebSocket.send (/home/ORNE/git_clone/app/node_modules/ws/lib/WebSocket.js:358:18)
    at require.sendFancy (/home/ORNE/git_clone/app/ws/eas.js:41:68)
    at Object.server.send [as callback] (/home/ORNE/git_clone/app/modules/mail.js:35:17)
    at Object._senddone (/home/ORNE/git_clone/app/node_modules/emailjs/smtp/client.js:199:13)
    at Object.<anonymous> (/home/ORNE/git_clone/app/node_modules/emailjs/smtp/client.js:188:96)
    at check (/home/ORNE/git_clone/app/node_modules/emailjs/smtp/client.js:150:18)
    at caller (/home/ORNE/git_clone/app/node_modules/emailjs/smtp/smtp.js:48:14)
    at response (/home/ORNE/git_clone/app/node_modules/emailjs/smtp/smtp.js:201:11)
    at caller (/home/ORNE/git_clone/app/node_modules/emailjs/smtp/smtp.js:48:14)
    at TLSSocket.response (/home/ORNE/git_clone/app/node_modules/emailjs/smtp/smtp.js:181:11)```

**Comment by GitSquared** [comment]
Second issue corrected by setting up `forever` properly.
